Repository twbs/icons, pull requests merged in 2020-06, with the labels that each got.

#282 Regenerate package-lock.json
  package-lock.json
Labels: dependencies

#288 Update some icons to remove transform attributes
  icons/brightness-high-fill.svg
  icons/brightness-low-fill.svg
  icons/brightness-low.svg
  icons/collection-fill.svg
Labels: bug

#275 Add PurgeCSS to the docs
  docs/assets/scss/_ads.scss
  docs/static/assets/css/bootstrap.min.css
  package-lock.json
  package.json
Labels: docs, enhancement

#302 Fix the OpenCollective link in the header
  config.yml
Labels: docs

#303 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/icon-request.md
Labels: docs

#307 Add 25 new icons
  bootstrap-icons.svg
  docs/content/icons/align-bottom.md
  docs/content/icons/align-center.md
  docs/content/icons/align-end.md
  docs/content/icons/align-middle.md
  docs/content/icons/align-start.md
  docs/content/icons/align-top.md
  docs/content/icons/bug-fill.md
  docs/content/icons/bug.md
  docs/content/icons/cpu-fill.md
  docs/content/icons/cpu.md
  docs/content/icons/distribute-horizontal.md
  docs/content/icons/distribute-vertical.md
  docs/content/icons/earbuds.md
  docs/content/icons/emoji-expressionless.md
  docs/content/icons/key-fill.md
  docs/content/icons/key.md
  docs/content/icons/mailbox.md
  docs/content/icons/mailbox2.md
  docs/content/icons/mouse.md
  docs/content/icons/mouse2.md
  docs/content/icons/mouse3.md
  docs/content/icons/sim-fill.md
  docs/content/icons/sim.md
  docs/content/icons/zoom-in.md
  docs/content/icons/zoom-out.md
  icons/align-bottom.svg
  icons/align-center.svg
  icons/align-end.svg
  icons/align-middle.svg
  icons/align-start.svg
  icons/align-top.svg
  icons/bug-fill.svg
  icons/bug.svg
  icons/cpu-fill.svg
  icons/cpu.svg
  icons/distribute-horizontal.svg
  icons/distribute-vertical.svg
  icons/earbuds.svg
  icons/emoji-expressionless.svg
  icons/key-fill.svg
  icons/key.svg
  icons/mailbox.svg
  icons/mailbox2.svg
  icons/mouse.svg
  icons/mouse2.svg
  icons/mouse3.svg
  icons/sim-fill.svg
  icons/sim.svg
  icons/zoom-in.svg
  icons/zoom-out.svg
Labels: enhancement

#317 Update favicons from Bootstrap v5.
  docs/layouts/partials/favicons.html
  docs/static/assets/img/favicons/android-chrome-192x192.png
  docs/static/assets/img/favicons/android-chrome-512x512.png
  docs/static/assets/img/favicons/apple-touch-icon.png
  docs/static/assets/img/favicons/browserconfig.xml
  docs/static/assets/img/favicons/favicon-16x16.png
  docs/static/assets/img/favicons/favicon-32x32.png
  docs/static/assets/img/favicons/favicon.ico
  docs/static/assets/img/favicons/manifest.json
  docs/static/assets/img/favicons/mstile-144x144.png
  docs/static/assets/img/favicons/mstile-150x150.png
  docs/static/assets/img/favicons/mstile-310x150.png
  docs/static/assets/img/favicons/mstile-310x310.png
  docs/static/assets/img/favicons/mstile-70x70.png
  docs/static/assets/img/favicons/safari-pinned-tab.svg
Labels: docs, enhancement

#316 Update devDependencies and regenerate package-lock.json
  package-lock.json
  package.json
Labels: dependencies

#324 Re-export a few icons to remove their strokes and outline a few vectors
  bootstrap-icons.svg
  icons/earbuds.svg
  icons/envelope.svg
  icons/journal-album.svg
  icons/sim.svg
  icons/tag.svg
Labels: bug
