Repository twbs/icons, pull requests merged in 2020-03, with the labels that each got.

#136 Adding release drafter action
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
Labels: docs

#138 Update skip icons
  icons/skip-backward-fill.svg
  icons/skip-end-fill.svg
  icons/skip-forward-fill.svg
  icons/skip-start-fill.svg
Labels: bug

#139 Fix text-right icon
  icons/text-right.svg
Labels: bug

#140 Make some filenames consistent
  book-half.svg
  icons/brightness-high-fill.svg
  icons/brightness-low-fill.svg
Labels: bug

#144 Add prerelease: true and exclude-labels to Release Drafter
  .github/release-drafter.yml
Labels: skip-changelog

#149 34 new icons, plus some renames
  icons/book-half.svg
  icons/briefcase.svg
  icons/chevron-double-down.svg
  icons/chevron-double-left.svg
  icons/chevron-double-right.svg
  icons/chevron-double-up.svg
  icons/circle-square.svg
  icons/clipboard-data.svg
  icons/clipboard.svg
  icons/columns-gap.svg
  icons/diamond-fill.svg
  icons/diamond.svg
  icons/exclude.svg
  icons/file-code.svg
  icons/file-diff.svg
  icons/file-richtext.svg
  icons/file-spreadsheet.svg
  icons/file-text.svg
  icons/file.svg
  icons/files-alt.svg
  icons/files.svg
  icons/funnel-fill.svg
  icons/funnel.svg
  icons/gem.svg
  icons/grid-1x2-fill.svg
  icons/grid-1x2.svg
  icons/grid-3x2-gap-fill.svg
  icons/grid-3x2-gap.svg
  icons/grid-3x2.svg
  icons/grid-3x3.svg
  icons/intersect.svg
  icons/layers-fill.svg
  icons/layers-half.svg
  icons/layers.svg
  icons/layout-sidebar-nested.svg
  icons/layout-three-columns.svg
  icons/layout-wtf.svg
  icons/newspaper.svg
  icons/octagon-fill.svg
  icons/octagon-half.svg
  icons/octagon.svg
  icons/paperclip.svg
  icons/people-circle.svg
  icons/subtract.svg
  icons/union.svg
Labels: feature

#108 Change navbar GitHub link to org
  config.yml
Labels: docs

#161 Add canonical meta tag
  docs/layouts/partials/header.html
Labels: docs

#172 Update icons.html
  docs/layouts/partials/icons.html
Labels: docs

#173 Reorganize Hugo variables
  config.yml
  docs/layouts/partials/footer.html
  docs/layouts/partials/hero.html
  docs/layouts/partials/navbar.html
Labels: docs

#181 Update shortcodes/example.html from upstream
  docs/layouts/shortcodes/example.html
Labels: docs

#186 Add list.js to the repo
  .eslintignore
  docs/layouts/partials/scripts.html
  docs/static/assets/js/list.min.js
Labels: dependencies, docs

#198 Remove unneeded `og:image:secure_url`
  docs/layouts/partials/social.html
Labels: docs

#194 Regenerate package-lock.json to fix a security vulnerability
  package-lock.json
Labels: dependencies

#199 Fix social meta tags title for homepage
  docs/layouts/partials/social.html
Labels: docs
