Repository twbs/icons, pull requests merged in 2020-05, with the labels that each got.

#247 Update config.yml
  config.yml
Labels: docs

#246 Regenerate package-lock.json
  package-lock.json
Labels: dependencies

#185 Update bootstrap to the current master code.
  docs/assets/scss/docs.scss
  docs/layouts/partials/icons.html
  docs/layouts/partials/stylesheet.html
  docs/static/assets/css/bootstrap.css
  docs/static/assets/css/bootstrap.min.css
Labels: dependencies, docs

#158 Add script to create permalink pages
  .eslintrc.json
  build/build-pages.js
  package.json
Labels: docs, enhancement

#259 Search by tags
  docs/layouts/partials/icons.html
  docs/layouts/partials/scripts.html
Labels: enhancement

#276 Improve icons layout
  docs/assets/scss/_clipboard-js.scss
  docs/assets/scss/_variables.scss
  docs/layouts/icons/single.html
Labels: docs
