Repository twbs/icons, pull requests merged in 2021-01, with the labels that each got.

#634 build-svgs: more tweaks
  .eslintrc.json
  build/build-svgs.js
Labels: enhancement

#636 Tweak build-pages.js
  build/build-pages.js
Labels: enhancement

#629 Docs: cache scripts partials in more cases
  docs/layouts/_default/404.html
  docs/layouts/_default/home.html
  docs/layouts/icons/single.html
  docs/layouts/partials/header.html
  docs/layouts/partials/navbar.html
Labels: docs, enhancement

#631 Switch to our svg-sprite fork
  package-lock.json
  package.json
Labels: dependencies

#650 Switch to `@twbs/svg-sprite`
  package-lock.json
  package.json
Labels: dependencies

#649 Add lockfile-lint
  package-lock.json
  package.json
Labels: enhancement

#658 Regenerate package-lock.json
  package-lock.json
Labels: dependencies

#659 CDN usage docs
  docs/assets/scss/docs.scss
  docs/content/_index.md
  docs/layouts/partials/hero.html
Labels: docs

#660 hero: remove `loading=lazy`
  docs/layouts/partials/hero.html
Labels: docs

#663 Remove quickstart link
  docs/layouts/partials/hero.html
Labels: docs

#596 fonts: generate woff2 first
  .fantasticonrc.js
  docs/assets/scss/docs.scss
  font/bootstrap-icons.css
Labels: enhancement

#661 homepage: link to issues
  docs/content/_index.md
Labels: docs

#689 Corrections/rewordings
  docs/content/_index.md
Labels: docs, enhancement
