Repository twbs/icons, pull requests merged in 2021-11, with the labels that each got.

#997 docs: move bootstrap.min.js to the application bundle
  docs/assets/js/vendor/bootstrap.min.js
  docs/layouts/partials/scripts.html
Labels: docs

#1053 docs: include the built font CSS
  docs/assets/scss/docs.scss
  docs/layouts/partials/stylesheet.html
Labels: docs

#1060 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#1069 Update Bootstrap to v5.1.3.
  docs/assets/js/vendor/bootstrap.min.js
  docs/static/assets/css/bootstrap.min.css
Labels: docs, dependencies

#1081 Update devDependencies
  .gitignore
  package-lock.json
  package.json
Labels: dependencies

#1089 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#1096 Bump to v1.7.1
  README.md
  config.yml
  docs/static/assets/img/bootstrap-icons-social.png
  package-lock.json
  package.json
Labels: release
