Repository twbs/icons, pull requests merged in 2022-05, with the labels that each got.

#1285 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#1312 Add `font-display: block`
  build/font/css.hbs
Labels: enhancement

#1331 Prep for v1.8.3 release
  config.yml
  docs/static/assets/img/bootstrap-icons-social.png
  package-lock.json
  package.json
Labels: release

#1333 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies
