Repository twbs/icons, pull requests merged in 2022-07, with the labels that each got.

#1348 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#1374 Update font Sass for more control over paths
  build/font/scss.hbs
  font/bootstrap-icons.scss
Labels: enhancement

#1369 docs: remove the now unused functions.scss
  docs/assets/scss/_functions.scss
Labels: docs
