Repository twbs/icons, pull requests merged in 2023-09, with the labels that each got.

#1713 Add paper plane tag to send icons
  docs/content/icons/send-check-fill.md
  docs/content/icons/send-check.md
  docs/content/icons/send-dash-fill.md
  docs/content/icons/send-dash.md
  docs/content/icons/send-exclamation-fill.md
  docs/content/icons/send-exclamation.md
  docs/content/icons/send-fill.md
  docs/content/icons/send-plus-fill.md
  docs/content/icons/send-plus.md
  docs/content/icons/send-slash-fill.md
  docs/content/icons/send-slash.md
  docs/content/icons/send-x-fill.md
  docs/content/icons/send-x.md
  docs/content/icons/send.md
Labels: docs

#1806 v1.11.0: Update blog post link, social image
  docs/layouts/partials/home/hero.html
  docs/static/assets/img/bootstrap-icons-social.png
Labels: release

#1707 Deploy: upload bootstrap icons zip
  .github/workflows/deploy.yml
Labels: build

#1812 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies
