Repository twbs/icons, pull requests merged in 2023-11, with the labels that each got.

#1872 Fix svg sprite
  package-lock.json
  package.json
Labels: dependencies

#1873 Fix Broken link in usage instructions
  docs/content/_index.md
Labels: docs

#1855 Added link to MIT License
  README.md
Labels: meta

#1876 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#1867 ban page: add block tag
  docs/content/icons/ban.md
Labels: docs
